name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - run: pip install -e '.[lint]'
    - run: ruff check .
    - run: pytype -j auto overcast_to_sqlite
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
    - run: pyroma .